services:
  hdfs-namenode:
      image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
      container_name: hdfs-namenode
      environment:
        - CLUSTER_NAME=test-cluster
      volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./start-hdfs.sh:/start-hdfs.sh
      - ../../data:/data
      ports:
        - "9870:9870"  # Namenode Web UI  
        - "8020:8020"  # Namenode IPC
      command: ["/bin/bash", "/start-hdfs.sh"]
      networks:
        - banking

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - CLUSTER_NAME=test-cluster
    volumes:
        - ./hadoop_config:/opt/hadoop/etc/hadoop
        - ./hadoop_datanode1:/opt/hadoop/data/dataNode
        - ./init-datanode.sh:/init-datanode.sh
    depends_on:
      - hdfs-namenode
    command: [ "/bin/bash", "./init-datanode.sh" ]
    networks:
      - banking

networks:
  banking:
    external: true