services:
  hdfs-namenode:
      image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
      container_name: hdfs-namenode
      environment:
        - CLUSTER_NAME=test-cluster
      ports:
        - "9870:9870"  # Web UI for HDFS NameNode
      networks:
        - default

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - CLUSTER_NAME=test-cluster
    depends_on:
      - hdfs-namenode
    networks:
      - default

networks:
  default:
    driver: bridge