version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge