services:
  airflow-db:
    image: postgres:14
    container_name: airflow-db
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AIRFLOW}
    ports:
      - "5434:5432"
    networks:
      - banking

  airflow-webserver:
    build:
      context: .
      dockerfile: ./airflow.Dockerfile
    container_name: airflow-webserver
    user: airflow
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@airflow-db:5432/${POSTGRES_AIRFLOW}
    ports:
      - "8082:8080"
    depends_on:
      - airflow-db
    volumes:
      - ../../data:/opt/airflow/data
      - ../../etl:/opt/airflow/dags
    command: 
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --role Admin --email admin@example.com --firstname Admin --lastname User &&
      airflow webserver"
    networks:
      - banking

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./airflow.Dockerfile
    container_name: airflow-scheduler
    user: airflow
    environment:
      - AIRFLOW__WEBSERVER__SECRET_KEY=airflow
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@airflow-db:5432/${POSTGRES_AIRFLOW}
    depends_on:
      - airflow-db
    volumes:
      - ../../data:/opt/airflow/data
      - ../../etl:/opt/airflow/dags
    command: scheduler
    networks:
      - banking

networks:
  banking:
    external: true